### ISSUE TITLE
demo account api key

### ISSUE THREAD

**Issue by roblewis1237** [aorzh/shopstyle_api#3]
hi @aorzh, thanks for sharing the repo, it's excellent. 

can i ask, how do you get api access with shopstyle? i've signed up for a demo account on their website and i have a key but I'm currently getting 401s (demo account not approved)

**Comment by aorzh** [comment]
Hi, @roblewis1237 I used my customer api key but as I see my own "test account" was blocked by shopstyle. I'll write to sopport because looks like they changed a bit their policy. Will back to you with information about demo api keys

**Comment by roblewis1237** [comment]
OK thanks @aorzh!

**Comment by aorzh** [comment]
@roblewis1237 , sorry for the long response. Did you tried to contact help@shopstylecollective.com ?
I submitted request for new developer account via https://shopstyle.typeform.com/to/yYV2za and waiting response. 
If you will have some updates also please let know as its will very helpful.

UPD:
Just got answer:
```We’ve received your application to be on ShopStyle and ShopStyle Collective. Thank you for your interest in partnering with us! For the time being, we are evaluating brands to be included on ShopStyle Collective only, and will reach out shortly upon review. Once we resume ShopStyle.com retailer onboarding, we will be in touch!```

How did you got api key and secret?

**Comment by roblewis1237** [comment]
Hi @aorzh, thanks for getting back to me. I've also filled in that form. But they haven't replied to me yet and I still get 401s on the "customer api key". 

I guess they've blocked access to it and aren't currently onboarding developers..

**Comment by aorzh** [comment]
@roblewis1237, I'll try to contact him and get some response. Maybe this tread will helpful for other developers.

**Comment by roblewis1237** [comment]
@aorzh - did they ever get back to you on this?

**Comment by aorzh** [comment]
No, any luck. My account was declined and I'm currently working on other projects

**Comment by aorzh** [comment]
Here is what I see in https://shopstylecollective.com/account/profile
`Your application has been denied.
Thank you for your interest in the ShopStyle Collective’s CPA program. Although your content has high potential, it doesn’t yet meet our criteria to extend an invitation. We’re sorry you’re not a fit at this time. We look at every account on an individual level to assess how it aligns with our community, and want you to join us in the future, so please keep us apprised of your growth. We look forward to being in touch in 2-3 months so we can reassess your application.`

**Comment by roblewis1237** [comment]
Ok thanks Alex. Shame they’ve changed their policy
